FROM node:22-alpine
ENV NODE_ENV=development
WORKDIR /opt/app
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev bash vips-dev git
RUN corepack enable
COPY package.json .pnpmrc pnpm-workspace.yaml ./
RUN pnpm install
COPY . .
RUN pnpm run build
EXPOSE 1337
CMD ["pnpm", "run", "start"]
